Dev
trailofbits/essence pull request #1
Opened 2021-08-16 12:38 UTC by sabastiaan

2021-08-16 15:40 UTC, woodruffw requested changes
Did an initial pass, looks good! Most feedback is C++ and Python best practices.

2021-08-16 15:40 UTC, woodruffw commented on .gitmodules
> +[submodule "argparse"]
Let's directly vendor this, as discussed 🙂

2021-08-16 15:40 UTC, woodruffw commented on CMakeLists.txt
> +set(CMAKE_RUNTIME_OUTPUT_DIRECTORY .)
It's normally a little bit of an antipattern to override `CMAKE_RUNTIME_OUTPUT_DIRECTORY` (and other CMake variables that control the default paths used to produce build outputs). What's your desired behavior here?

2021-08-16 15:40 UTC, woodruffw commented on README.md
> +This project aims to extract functions from llvm bitcode files and generate executables for them.
```suggestion
This project aims to extract individual functions from LLVM bitcode files and generate executables for them.
```

2021-08-16 15:40 UTC, woodruffw commented on README.md
> +Functions can be specified by name and convenient json input templates will be generated in which their arguments (including globals) can be specified.
```suggestion
Functions can be specified by name and convenient JSON input templates will be generated in which their arguments (including globals) can be specified.
```

2021-08-16 15:40 UTC, woodruffw commented on README.md
> +The project is sub-devided into two components: `Essence` is the python tool which is meant for users and handles all of the end to end functionality, and `Handsanitizer` which is the c++ component w
```suggestion
The project is subdivided into two components: `Essence` is the Python tool which is meant for users and handles all of the end to end functionality, and `Handsanitizer` which is the C++ component which interacts directly with the LLVM bitcode modules and generates necessary code/templates.
```

(Also, is the capitalization on these tools here consistent with how they're used from the CLI?)

2021-08-16 15:40 UTC, woodruffw commented on README.md
> +Our focus is primarly "pure" functions. There are two major categories of pure functions
```suggestion
Our focus is primarly "pure" functions. There are two major categories of pure functions:
```

2021-08-16 15:40 UTC, woodruffw commented on README.md
> +1. `read none`:
N.B.: You can use `1.` multiple times in Markdown to have the renderer perform auto-numbering for you. Not a big deal since we only have two elements here, but something to know!

2021-08-16 15:40 UTC, woodruffw commented on README.md
> +   Additionally a `read none` functions are not allowed to have side-effects and hence are not allowed to touch memory at all.
Nit: they're allowed to touch *local* memory, as long as LLVM can prove that the local changes don't escape the function.

2021-08-16 15:40 UTC, woodruffw commented on README.md
> +$ sudo apt install nlohmann-json3-dev
We should also vendor this dependency, since it's a single header file.

2021-08-16 15:40 UTC, woodruffw commented on README.md
> +#### essence <input.bc>
Use backticks for the headers here and below to prevent formatting confusion:

```suggestion
#### `essence <input.bc>`
```

2021-08-16 15:40 UTC, woodruffw commented on README.md
>  ```
```suggestion
```c
```

2021-08-16 15:40 UTC, woodruffw commented on README.md
> +   "int_val_ptr_1": 30, # sets 30 at the addressed referenced by int_val_ptr,
N.B.: Try using `//` for comments here. JSON technically doesn't support comments at all, but `//` is accepted by more parsers than `#`.

2021-08-16 15:40 UTC, woodruffw commented on handsanitizer/DeclarationManager.cpp
> +    std::string DeclarationManager::getRandomDummyVariableName() {
`TmpStringCandidates` lives longer than this function, so you can return `std::string&` here. 

You can also make this more defensive by marking both the function and the return as `const`:

```suggestion
    const std::string& DeclarationManager::getRandomDummyVariableName() const {
```

2021-08-16 15:40 UTC, woodruffw commented on handsanitizer/DeclarationManager.h
> +    std::vector<Type*> user_defined_types;
Nit: consistent naming: you use both `snake_case` and `camelCase` in this class, stick with one (either is fine!)

2021-08-16 15:40 UTC, woodruffw commented on handsanitizer/DeclarationManager.h
> +    std::vector<std::string> iterator_names;
N.B.: This could probably be a `std::set` for faster inserts/lookups?

2021-08-16 15:40 UTC, woodruffw commented on handsanitizer/DeclarationManager.h
> +    std::vector<std::string> other_disallowed_names;
Same with this, maybe make it a `std::set`?

2021-08-16 15:40 UTC, woodruffw commented on handsanitizer/FunctionCallerGenerator.cpp
> +    void FunctionCallerGenerator::generate_json_input_template_file(std::string dest_file_path) {
You might have explained this already, but why are we avoiding the `nhlohmann::json` APIs for constructing the JSON here?

2021-08-16 15:40 UTC, woodruffw commented on handsanitizer/FunctionCallerGenerator.cpp
> +        of.close();
```suggestion
```

You can safely delete this; `of` will be auto-closed thanks to RAII.

2021-08-16 15:40 UTC, woodruffw commented on handsanitizer/FunctionCallerGenerator.cpp
> +        of.open(dest_file_path, std::ofstream::out | std::ofstream::trunc);
Prefer direct initialization wherever possible:

```suggestion
        std::ofstream of(dest_file_path.c_str(), std::ofstream::out | std::ofstream::trunc);
```

2021-08-16 15:40 UTC, woodruffw commented on handsanitizer/FunctionCallerGenerator.cpp
> +    void FunctionCallerGenerator::generate_json_input_template_file(std::string dest_file_path) {
```suggestion
    void FunctionCallerGenerator::generate_json_input_template_file(const std::string& dest_file_path) {
```

2021-08-16 15:40 UTC, woodruffw commented on handsanitizer/FunctionCallerGenerator.cpp
> +    void FunctionCallerGenerator::generate_cpp_file_for_function(std::string dest_file_path) {
Use `const` and references wherever you don't need mutability or your own copy of the object:

```suggestion
    void FunctionCallerGenerator::generate_cpp_file_for_function(const std::string& dest_file_path) {
```

2021-08-16 15:40 UTC, woodruffw commented on handsanitizer/FunctionCallerGenerator.cpp
> +    std::vector<GlobalVariable> FunctionCallerGenerator::getGlobals() {
If callers shouldn't be able to modify the inner object, `const`ify and reference it:

```suggestion
    const std::vector<GlobalVariable>& FunctionCallerGenerator::getGlobals() const {
```

2021-08-16 15:40 UTC, woodruffw commented on handsanitizer/JsonInputParser.h
> +    explicit JsonInputParser(std::shared_ptr<DeclarationManager> declarationManager) : declarationManager(declarationManager) {};
👍  for using `explicit`

2021-08-16 15:40 UTC, woodruffw commented on handsanitizer/JsonInputParser.h
> +    std::string getParserRetrievalForNamedType(std::string jsonInputVariableName, std::vector<std::string> prefixes, handsanitizer::Type* type, bool isForGlobals = false);
N.B.: mark each/all of these as `const std::string&` or as a const function, if appropriate.

2021-08-16 15:40 UTC, woodruffw commented on handsanitizer/LLVMExtractor.cpp
> +        if(structName == "")
```suggestion
        if (structName.empty())
```

2021-08-16 15:40 UTC, woodruffw commented on handsanitizer/LLVMExtractor.cpp
> +            structName = structName.replace(0, 7, ""); //removes struct. prefix
N.B.: You can avoid the assignment here by removing the prefix in-place with `erase`.

2021-08-16 15:40 UTC, woodruffw commented on handsanitizer/LLVMExtractor.cpp
> +            structName = structName.replace(0, 6, ""); //removes union. prefix
Same here.

2021-08-16 15:40 UTC, woodruffw commented on handsanitizer/LLVMExtractor.cpp
> +            std::shared_ptr<DeclarationManager> declarationManager = std::make_shared<DeclarationManager>();
I might be missing the reason here, but why does `declarationManafer` need to be a shared pointer?

2021-08-16 15:40 UTC, woodruffw commented on handsanitizer/LLVMExtractor.cpp
> +        }
N.B.: You don't *need* to do this, but you can avoid this kind of ugly post-loop fixup by checking whether you're on the final iteration within the loop itself:

```c++
for (const auto& args : this->arguments) {
  // ...
  if (&args == &*this->arguments.rbegin()) {
    // this is the last element
  }
}
```

(This only works for by-ref iterators, though.)

2021-08-16 15:40 UTC, woodruffw commented on handsanitizer/LLVMExtractor.cpp
> +    std::string Function::getPurityName() {
Consider lifting the string literals here to a class-level constant map, and changing the signature:

```suggestion
    const std::string& Function::getPurityName() const {
```

(Otherwise, this produces a lot of unnecessary copies.)

2021-08-16 15:40 UTC, woodruffw commented on handsanitizer/SpecificationPrinter.cpp
> +        return outputFilePath;
You shouldn't have to round-trip through `string()` for paths here -- if you want a new path, you can remain within the filesystem types.

2021-08-16 15:40 UTC, woodruffw commented on handsanitizer/main.cpp
> +        std::filesystem::create_directory(output_dir);
Skip the `exists` check here by using `create_directories` instead of `create_directory`.

2021-08-16 15:40 UTC, woodruffw commented on src/essence/cli.py
> +handsan_path = dirname + "/../../HandSanitizer"
N.B. Use `Path` objects and their API here; they're more misuse-resistant.

2021-08-16 15:40 UTC, woodruffw commented on src/essence/cli.py
> +    input_file = args.input
```suggestion
    input_file = Path(args.input)
```

etc.

2021-08-16 15:40 UTC, woodruffw commented on src/essence/cli.py
> +    if pathlib.Path(input_file).suffix == '.c':
If you construct `input_file`, etc as `Paths`, you don't need an inline constructor here!

2021-08-16 15:40 UTC, woodruffw commented on src/essence/cli.py
> +        return;
```suggestion
        return
```

2021-08-16 15:40 UTC, woodruffw commented on src/essence/cli.py
> +        print("got .c file as input, you probably meant .bc")
Use `stderr` for errors and warnings:

```
print("...", file=sys.stderr)
```

2021-08-16 15:40 UTC, woodruffw commented on src/essence/cli.py
> +        contents = json.loads(j.read())
Use the direct IO form:

```suggestion
        contents = json.load(j)
```

2021-08-16 15:40 UTC, woodruffw commented on src/essence/cli.py
> +    with open(spec_path, 'r') as j:
N.B.: If you make `spec_path` into a `Path` object, you can do this:

```python
with spec_path.open("r") as j:
    # ...
```

2021-08-16 15:40 UTC, woodruffw commented on src/essence/cli.py
> +        funcs = filter(lambda content: content['purity'] == purity_level, funcs)
Always prefer list comprehensions over `filter`:

```python
funcs = [func for func in funcs if func["purity"] == purity_level]
```

2021-08-17 11:05 UTC, sabastiaan commented on handsanitizer/FunctionCallerGenerator.cpp
> +    void FunctionCallerGenerator::generate_json_input_template_file(std::string dest_file_path) {
No good reason really. After the auto-mapping didn't work due to pointers being treated differently I switched to a manual implementation ditching the API all together, but I could switch to a less string based approached here indeed!

2021-08-17 11:12 UTC, sabastiaan commented on handsanitizer/LLVMExtractor.cpp
> +            std::shared_ptr<DeclarationManager> declarationManager = std::make_shared<DeclarationManager>();
This object is passed to both `jsonInputGenerator` and `jsonOutputGenerator` inside the constructor of a `functionCallerGenerator` and need to be shared between both. Since it would be converted to a `shared_ptr` anyway I opted to do it from the beginning. Otherwise I would have made it a `unique_ptr` for `functionCallerGenerator`

2021-08-17 11:16 UTC, sabastiaan commented on CMakeLists.txt
> +set(CMAKE_RUNTIME_OUTPUT_DIRECTORY .)
I messed up my build system once such that it didn't output the binary in the root of the project on build and this fixed it. I could probably remove this

2021-08-18 14:01 UTC, woodruffw commented on handsanitizer/FunctionCallerGenerator.cpp
> +    void FunctionCallerGenerator::generate_json_input_template_file(std::string dest_file_path) {
Yep, I think that would be good to do -- it'll be a lot easier to maintain.

2021-08-18 14:15 UTC, woodruffw commented on setup.py
> +            "essence-hello = essence.cli:hello"
This should probably be removed 🙂

2021-08-19 12:08 UTC, sabastiaan commented on README.md
> +This project aims to extract functions from llvm bitcode files and generate executables for them.
If we have a pure function that calls another pure function, then we currently extract both into the same new module. So I'm not sure if individual would be correct here.

2021-08-19 14:07 UTC, woodruffw commented on README.md
> +This project aims to extract functions from llvm bitcode files and generate executables for them.
Yeah, I see what you mean. Perhaps "aims to extract pure functions from LLVM bitcode [...]" and then a second sentence saying something like "multiple functions are extracted if a pure function contains calls to other pure functions."?

2021-08-26 16:11 UTC, sabastiaan commented on README.md
> +This project aims to extract functions from llvm bitcode files and generate executables for them.
I changed the wording to lean more on generating stand-alone executable instead of extracting functions since the extraction is actually just an implementation detail as we could have linked against the original bc module.

2021-08-26 18:04 UTC, woodruffw approved these changes
LGTM. There are other QoL improvements we could make, but this is good for an initial version.

2021-08-26 18:05 UTC, merged